package com.fredhli.flowwidget

import android.content.Context
import android.content.Intent
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.collectAsState
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.emptyPreferences
import androidx.glance.ColorFilter
import androidx.glance.GlanceId
import androidx.glance.GlanceModifier
import androidx.glance.Image
import androidx.glance.ImageProvider
import androidx.glance.LocalContext
import androidx.glance.LocalSize
import androidx.glance.action.clickable
import androidx.glance.appwidget.GlanceAppWidget
import androidx.glance.appwidget.SizeMode
import androidx.glance.appwidget.action.actionStartActivity
import androidx.glance.appwidget.appWidgetBackground
import androidx.glance.appwidget.cornerRadius
import androidx.glance.appwidget.lazy.LazyColumn
import androidx.glance.appwidget.lazy.items
import androidx.glance.appwidget.provideContent
import androidx.glance.background
import androidx.glance.color.ColorProvider
import androidx.glance.layout.Alignment
import androidx.glance.layout.Box
import androidx.glance.layout.Column
import androidx.glance.layout.ContentScale
import androidx.glance.layout.Row
import androidx.glance.layout.Spacer
import androidx.glance.layout.fillMaxSize
import androidx.glance.layout.fillMaxWidth
import androidx.glance.layout.height
import androidx.glance.layout.padding
import androidx.glance.layout.size
import androidx.glance.layout.width
import androidx.glance.text.FontWeight
import androidx.glance.text.Text
import androidx.glance.text.TextStyle

/**
 * The Flow widget, redesigned per design/BRIEF.md ("Bixby's surface + Gmail's feed"):
 * a translucent diagonal-gradient glass container (GlassSurface, opacity user-set in
 * the config screen), Gmail-shaped feed rows carrying their own subtle fill that does
 * the legibility work, generous §3 spacing, the system font throughout.
 *
 * Two responsive buckets — 4x2 (header + compact rows) and 4x3 (header + rows with a
 * meta line). Paints from the DataStore cache, so it renders instantly after reboot
 * and never goes blank on a failed fetch.
 */
class FlowWidget : GlanceAppWidget() {

    override val sizeMode: SizeMode = SizeMode.Responsive(setOf(COMPACT, TALL))

    override suspend fun provideGlance(context: Context, id: GlanceId) {
        val store = FlowStore.get(context)
        // Load BEFORE composing. Glance publishes the first idle composition straight to
        // the host, and a DataStore read started from inside the composition cannot beat
        // that idle — so composing against a null placeholder pushes a near-empty
        // RemoteViews to the launcher on every session start (the post-reboot repaint,
        // every 30-minute fetch, every 15-minute tick). With the snapshot already in hand
        // the first frame is the cached feed, which is the "never blank" contract.
        val initial = runCatching { store.snapshot() }.getOrElse { emptyPreferences() }
        provideContent {
            val prefs by store.data.collectAsState(initial = initial)
            WidgetBody(prefs)
        }
    }

    companion object {
        /** 4x2 — header + compact rows. */
        val COMPACT = DpSize(250.dp, 110.dp)

        /** 4x3 — header + rows with meta line. */
        val TALL = DpSize(250.dp, 180.dp)
    }
}

// ------------------------------------------------------------------ glass surface

/**
 * The container surface, one drawable per opacity level, indexed by
 * [GlassSurface.levelFor]. Each id resolves to `res/drawable/glass_NN.xml` in light and
 * `res/drawable-night/glass_NN.xml` in dark — and, crucially, it is the *host* that
 * resolves it, at apply time, against its own configuration. That is what makes the
 * surface follow a system dark-mode flip the way the text already did; a bitmap baked at
 * composition time could not, and left night ink on a day surface at 1.03:1 until the
 * next composition. See GlassSurface's header for the full argument and for the other two
 * defects the move cured (the stretched corner radius and ~2 MB of bitmap per update).
 *
 * Generated by `tools/gen-glass-drawables.py`; re-run it with `--check` to prove the
 * resources and the level math have not drifted apart.
 */
private val GlassLevels = intArrayOf(
    R.drawable.glass_00, R.drawable.glass_01, R.drawable.glass_02, R.drawable.glass_03,
    R.drawable.glass_04, R.drawable.glass_05, R.drawable.glass_06, R.drawable.glass_07,
    R.drawable.glass_08, R.drawable.glass_09, R.drawable.glass_10, R.drawable.glass_11,
    R.drawable.glass_12, R.drawable.glass_13, R.drawable.glass_14, R.drawable.glass_15,
)

// ------------------------------------------------------------------ palette

// Explicit day/night providers instead of GlanceTheme: the surface is a translucent
// gradient the wallpaper glows through, so text needs known-contrast colors, not the
// opaque-surface roles of a Material scheme. The accent is the Flow violet — the
// non-negotiable identity color for the kind glyph, the unread dot and the updating note.
private val AccentColor = ColorProvider(day = Color(0xFF7C3AED), night = Color(0xFFA78BFA))
private val TitleColor = ColorProvider(day = Color(0xFF1B1C22), night = Color(0xFFF3F2F8))

/** Meta/secondary ink: the title ink at 70% (design/RESEARCH.md §3). */
private val MetaColor = ColorProvider(day = Color(0xB31B1C22), night = Color(0xB3F3F2F8))

/** Stale (>24 h) ink: 55% — visibly grey against TitleColor but still legible on glass. */
private val StaleColor = ColorProvider(day = Color(0x8C1B1C22), night = Color(0x8CF3F2F8))

/**
 * Row fill — the legibility mechanism that replaces blur (RESEARCH.md §1, §4b: ~45%).
 *
 * 45% white in light, 9% white in dark, and the asymmetry is not a typo: white on a light
 * container lifts the row *away* from dark ink, white on a near-black container lifts it
 * *towards* light ink. So the fill does the legibility work in light mode and only the
 * row-shape work in dark, where the container's own opacity floor
 * ([GlassSurface.MIN_OPACITY_DARK]) is what keeps a bright wallpaper off the text.
 */
private val RowFill = ColorProvider(day = Color(0x73FFFFFF), night = Color(0x17FFFFFF))

/**
 * The compact row's minimum content height, so a one-line title still clears the 48dp
 * tap minimum: 48 - 2 x the 8dp compact row padding. See the strut in [ItemRow].
 */
private val COMPACT_ROW_MIN_CONTENT = 32.dp

// ------------------------------------------------------------------ derived state

internal data class UiState(
    val configured: Boolean,
    val baseUrl: String,
    val feed: Feed?,
    val offline: Boolean,
    val refreshing: Boolean,
    val stale: Boolean,
    /** The header band's label: "32min ago" — when the feed was last generated. */
    val ageText: String,
    val lastOpenMs: Long,
    val bgOpacity: Float,
)

internal fun deriveState(prefs: Preferences, nowMs: Long): UiState {
    val cfg = FlowStore.configFrom(prefs)
    val feed = prefs[FlowStore.KEY_FEED_JSON]?.let {
        runCatching { FeedParser.parse(it) }.getOrNull()
    }
    val offline = prefs[FlowStore.KEY_FETCH_OK] == false
    val latestMs = RelativeAge.parseTs(feed?.latest)
    return UiState(
        configured = cfg != null,
        baseUrl = cfg?.baseUrl ?: FlowStore.DEFAULT_BASE_URL,
        feed = feed,
        offline = offline,
        // The server's flag is now the only source of the updating state: the widget
        // has no refresh control of its own, so a run always starts on the Flow page
        // and reaches the widget through `refreshing` in the next GET.
        refreshing = feed?.refreshing == true,
        stale = RelativeAge.isStale(latestMs, nowMs),
        ageText = RelativeAge.ago(latestMs, nowMs),
        lastOpenMs = prefs[FlowStore.KEY_LAST_OPEN] ?: 0L,
        bgOpacity = GlassSurface.clampOpacity(prefs[FlowStore.KEY_BG_OPACITY]),
    )
}

/** What the body area shows. Split out of the composable so it can be tested. */
internal enum class BodyMode {
    /** Never configured: tap opens the config screen. */
    SETUP,

    /** Configured, but the server has never answered — a dead end without a way back. */
    UNREACHABLE,

    /** Configured, no cache yet, no failure recorded: the first fetch is in flight. */
    LOADING,

    /** The server answered with an empty batch. */
    EMPTY,

    /** The normal case. */
    LIST,
}

internal fun bodyMode(state: UiState): BodyMode = when {
    !state.configured -> BodyMode.SETUP
    // Offline with nothing cached is terminal, not transient: a mistyped token saved
    // through "Save anyway", or a server that was down when the widget was added, leaves
    // the widget here forever. "Loading…" would be a lie, and with no launcher icon the
    // only route back is a One UI gesture nobody remembers — so offer the config screen.
    state.offline && state.feed == null -> BodyMode.UNREACHABLE
    state.feed == null -> BodyMode.LOADING
    state.feed.items.isEmpty() -> BodyMode.EMPTY
    else -> BodyMode.LIST
}

/**
 * The row's meta line ("progress · 1 h"): kind word + relative age. There is no source
 * field in the feed (FeedItem is id/title/ts/kind), so the kind word stands where the
 * mockup shows a source. Pure so it is testable off-device.
 */
internal fun metaLine(item: FeedItem, nowMs: Long): String {
    val ts = RelativeAge.parseTs(item.ts) ?: return item.kind
    return "${item.kind} · ${RelativeAge.format(ts, nowMs)}"
}

// ------------------------------------------------------------------ layout

@Composable
private fun WidgetBody(prefs: Preferences) {
    val now = System.currentTimeMillis()
    val state = deriveState(prefs, now)
    val size = LocalSize.current
    val tall = size.height >= 160.dp
    // Note what is NOT read here: the night-mode bit. The surface is a day/night drawable
    // resource the launcher resolves at apply time, so nothing in this composition needs
    // to know which theme it will be painted in — which is exactly why the surface now
    // survives a system dark-mode flip between compositions.
    val glass = GlassLevels[GlassSurface.levelFor(state.bgOpacity)]
    Box(
        modifier = GlanceModifier
            .fillMaxSize()
            .appWidgetBackground()
            .background(ImageProvider(glass), contentScale = ContentScale.FillBounds)
            .cornerRadius(24.dp)
            // §3 container padding: 16dp sides. Vertically the deviation is deliberate and
            // recorded in design/BRIEF.md's spacing table as its own column: the 48dp
            // header band centres its own text and so pays for the top itself, and the
            // bottom is what the 110dp compact bucket can still afford under a whole row.
            .padding(horizontal = 16.dp)
            .padding(bottom = if (tall) 10.dp else 4.dp)
    ) {
        Column(modifier = GlanceModifier.fillMaxSize()) {
            Header(state)
            // An inert gutter between two differently-actioned targets: the band opens
            // `#/flow`, item row 1 opens that item. Round 1 left 2dp here on the reasoning
            // that deleting the refresh glyph left "no neighbouring target to mis-hit" —
            // false, the first row is that neighbour, and it sat 1.8dp away. 8dp is
            // DESIGN-NOTES entry 1's number; the compact bucket pays 6dp, matching its own
            // inter-row gap, because 8 would crop the single row it can draw.
            Spacer(GlanceModifier.height(if (tall) 8.dp else 6.dp))
            // The weight lives here: defaultWeight() is a ColumnScope extension and
            // does not resolve inside the child composables.
            Box(modifier = GlanceModifier.fillMaxWidth().defaultWeight()) {
                when (bodyMode(state)) {
                    BodyMode.SETUP -> SetupNote("Tap to set up Flow")
                    BodyMode.UNREACHABLE -> SetupNote("Can't reach Flow — tap to set up")
                    BodyMode.LOADING -> CenteredNote("Loading…")
                    BodyMode.EMPTY -> CenteredNote("No flow yet")
                    BodyMode.LIST -> ItemList(state, tall, now)
                }
            }
        }
    }
}

/**
 * The header band (design/BRIEF.md § "The header band", amended 2026-09-01).
 *
 * There is no refresh control: a tap trigger on a home-screen widget is a mis-touch
 * magnet, and refreshing is the Flow page's job. So the band carries only what it says —
 * "Flow" on the left, the feed's last-generation age on the right — and the *whole* band,
 * full width and a fixed 48dp tall, is one tap target opening `#/flow` (through the
 * trampoline, so the unread dots clear on the way).
 *
 * The inert gutter DESIGN-NOTES entry 1 asked to preserve is still needed, and lives in
 * [WidgetBody] as the spacer under this band. Deleting the refresh glyph removed one
 * neighbouring target, not all of them: item row 1 fires a different action (that item,
 * not the feed) and is the band's new neighbour.
 */
@Composable
private fun Header(state: UiState) {
    val context = LocalContext.current
    Row(
        modifier = GlanceModifier
            .fillMaxWidth()
            .height(48.dp)
            .clickable(
                actionStartActivity(
                    Intent(context, OpenItemActivity::class.java)
                        .putExtra(OpenItemActivity.EXTRA_URL, "${state.baseUrl}/#/flow")
                )
            ),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            text = "Flow",
            style = TextStyle(
                color = TitleColor,
                fontSize = 15.sp,
                // §3 asks for weight 600; Glance exposes 400/500/700 and Medium(500)
                // reads too light next to the mockup — Bold is the closer match.
                fontWeight = FontWeight.Bold,
            ),
        )
        Spacer(GlanceModifier.defaultWeight())
        if (state.offline) {
            Image(
                provider = ImageProvider(R.drawable.ic_offline),
                contentDescription = context.getString(R.string.cd_offline),
                modifier = GlanceModifier.size(14.dp),
                colorFilter = ColorFilter.tint(MetaColor),
            )
            Spacer(GlanceModifier.width(6.dp))
        }
        // The one age in the widget's chrome, on the right, in the meta grey — and the
        // updating note in its place while the server says a run is in flight, which is
        // how a refresh started from the web page shows up here.
        Text(
            text = if (state.refreshing) "updating…" else state.ageText,
            style = TextStyle(
                color = if (state.refreshing) AccentColor else MetaColor,
                fontSize = 12.sp,
            ),
            maxLines = 1,
        )
    }
}

@Composable
private fun ItemList(state: UiState, tall: Boolean, nowMs: Long) {
    val context = LocalContext.current
    val feed = state.feed ?: return
    val gap = if (tall) 8.dp else 6.dp
    LazyColumn(modifier = GlanceModifier.fillMaxSize()) {
        items(feed.items) { item ->
            Box(modifier = GlanceModifier.padding(bottom = gap)) {
                ItemRow(
                    context = context,
                    item = item,
                    baseUrl = state.baseUrl,
                    stale = state.stale,
                    unread = isUnread(item, state.lastOpenMs),
                    tall = tall,
                    nowMs = nowMs,
                )
            }
        }
    }
}

internal fun isUnread(item: FeedItem, lastOpenMs: Long): Boolean {
    val ts = RelativeAge.parseTs(item.ts) ?: return false
    return ts > lastOpenMs
}

@Composable
private fun ItemRow(
    context: Context,
    item: FeedItem,
    baseUrl: String,
    stale: Boolean,
    unread: Boolean,
    tall: Boolean,
    nowMs: Long,
) {
    val titleColor = if (stale) StaleColor else TitleColor
    val glyph = if (item.kind == FeedParser.KIND_PROGRESS) R.drawable.ic_progress else R.drawable.ic_headline
    val glyphCd = if (item.kind == FeedParser.KIND_PROGRESS) R.string.cd_progress else R.string.cd_headline
    Row(
        modifier = GlanceModifier
            .fillMaxWidth()
            // The row fill is what earns legibility on the translucent surface.
            .background(RowFill)
            .cornerRadius(16.dp)
            // §3: 12dp vertical / 14dp horizontal at 4x3. The compact bucket trades that
            // down to 8dp (and drops the meta line) so a two-line row clears the 110dp
            // bucket floor under the 48dp header band — 12dp would make it 59dp against a
            // 52dp body. That trade is NOT §3 working as written, whatever DESIGN-NOTES
            // used to say about it; it is a compact-bucket column in design/BRIEF.md's
            // spacing table, recorded there so the next round does not "restore" it.
            .padding(horizontal = 14.dp, vertical = if (tall) 12.dp else 8.dp)
            .clickable(
                actionStartActivity(
                    Intent(context, OpenItemActivity::class.java)
                        .putExtra(OpenItemActivity.EXTRA_URL, "$baseUrl/#/flow/i/${item.id}")
                )
            ),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        // The glyph's box is also the compact row's height floor. The row wraps its
        // content, so a title short enough to fit one line — a CJK headline at the bottom
        // of FLOW_SPEC's 10-24 字 range, "Backfill done" — made the row ~35 dp: an
        // action-firing target 13 dp under the minimum this project holds itself to, right
        // beside another row's target. Padding cannot fix it (15 dp of padding would make
        // the two-line row 65 dp against a 52 dp body); a minimum can, and giving it to
        // the glyph costs no extra view. Because it is a floor and not a fixed height, a
        // two-line title — or a large system font scale — still grows the row past it.
        Box(
            modifier = GlanceModifier
                .width(16.dp)
                .height(if (tall) 16.dp else COMPACT_ROW_MIN_CONTENT),
            contentAlignment = Alignment.Center,
        ) {
            Image(
                provider = ImageProvider(glyph),
                contentDescription = context.getString(glyphCd),
                modifier = GlanceModifier.size(16.dp),
                colorFilter = ColorFilter.tint(if (stale) StaleColor else AccentColor),
            )
        }
        Spacer(GlanceModifier.width(10.dp))
        Column(modifier = GlanceModifier.defaultWeight()) {
            // §3 asks for 14sp at line-height 1.35. The size is honoured; the line height
            // cannot be — Glance 1.1.1's TextStyle has seven fields (color, fontSize,
            // fontWeight, fontStyle, textAlign, textDecoration, fontFamily) and no
            // lineHeight, verified against the shipped glance-1.1.1.aar. The platform
            // default renders 1.17, ~6px per line under spec. Recorded beside blur and
            // bundled fonts in design/RESEARCH.md §2 rather than left reading as met; the
            // row's own padding is what buys the breathing room instead.
            Text(
                text = item.title,
                style = TextStyle(color = titleColor, fontSize = 14.sp),
                maxLines = 2,
            )
            if (tall) {
                Spacer(GlanceModifier.height(3.dp))
                Text(
                    text = metaLine(item, nowMs),
                    style = TextStyle(
                        color = if (stale) StaleColor else MetaColor,
                        fontSize = 12.sp,
                    ),
                    maxLines = 1,
                )
            }
        }
        if (unread) {
            Spacer(GlanceModifier.width(8.dp))
            Box(
                modifier = GlanceModifier
                    .size(7.dp)
                    .cornerRadius(4.dp)
                    .background(AccentColor)
            ) {}
        }
    }
}

@Composable
private fun SetupNote(text: String) {
    val context = LocalContext.current
    Box(
        modifier = GlanceModifier
            .fillMaxSize()
            .clickable(actionStartActivity(Intent(context, ConfigActivity::class.java))),
        contentAlignment = Alignment.Center,
    ) {
        NotePill(text)
    }
}

@Composable
private fun CenteredNote(text: String) {
    Box(modifier = GlanceModifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        NotePill(text)
    }
}

/** State notes sit in a row-styled pill so they read on the glass like the feed does. */
@Composable
private fun NotePill(text: String) {
    Box(
        modifier = GlanceModifier
            .background(RowFill)
            .cornerRadius(16.dp)
            .padding(horizontal = 16.dp, vertical = 10.dp)
    ) {
        Text(
            text = text,
            style = TextStyle(color = MetaColor, fontSize = 13.sp),
            maxLines = 2,
        )
    }
}
