package com.fredhli.flowwidget

/**
 * The redesign's translucent "glass" container surface (design/BRIEF.md + RESEARCH.md):
 * a diagonal three-stop gradient — grey → blue-tint → grey — of alpha colors. No blur: a
 * widget is RemoteViews inside the launcher's window and cannot invoke the window-owner
 * blur APIs (RESEARCH.md §1), so legibility comes from the row fill on top of this
 * surface and from the surface's own opacity, not from blur.
 *
 * **The surface is a drawable resource, not a bitmap.** Round 1 baked it into an
 * ARGB_8888 Bitmap at composition time; three separate defects came out of that at review
 * and all three are cured by moving it into `res/drawable/glass_NN.xml` +
 * `res/drawable-night/glass_NN.xml` (generated by `tools/gen-glass-drawables.py`):
 *
 *  1. **A baked bitmap freezes the theme.** Every other colour here is a Glance day/night
 *     `ColorProvider`, which the launcher re-resolves when it re-applies its cached
 *     RemoteViews under a new night configuration. The bitmap could not be, so a system
 *     dark-mode flip left night ink on a day surface — 1.03:1, invisible — until the next
 *     composition, up to a Doze-stretched 15 minutes away. A resource id goes to the host
 *     as `setImageViewResource` and is resolved against the *host's* configuration at
 *     apply time, so the surface now flips with the text.
 *  2. **A baked corner radius was drawn at the wrong size.** Under `SizeMode.Responsive`
 *     `LocalSize` is the declared bucket, not the widget's real bounds, and the background
 *     is stretched with `ContentScale.FillBounds` — so the 24 dp corner reached a real
 *     home screen as a stretched ellipse outside the `cornerRadius(24.dp)` outline clip,
 *     with a transparent wallpaper crescent between the two. A `GradientDrawable` has no
 *     intrinsic size, so the hosting `ImageView` gives it the real view bounds: the baked
 *     corner and the outline clip now coincide at exactly 24 dp, at any placement size.
 *  3. **~2 MB of bitmap per update**, allocated twice (once per responsive bucket) and
 *     marshalled to the launcher on every tick, fetch and tap, for a three-stop gradient.
 *     A resource id costs four bytes.
 *
 * The price is that the opacity slider — a continuous float in DataStore — has to land on
 * one of a fixed set of resources. [LEVELS] levels 3% apart span the brief's 0.50 → 0.95
 * range and hit both documented numbers exactly: the 0.74 default is level 8, the 0.80
 * dark floor is level 10. Neighbouring levels are indistinguishable, so the slider still
 * reads as continuous.
 *
 * All of this is pure Kotlin so it can be unit-tested off-device; the resource table
 * itself lives in FlowWidget.kt, next to the composable that uses it.
 */
object GlassSurface {

    /** Slider range, design/BRIEF.md § "The surface". Light theme. */
    const val MIN_OPACITY = 0.50f
    const val MAX_OPACITY = 0.95f
    const val DEFAULT_OPACITY = 0.74f

    /**
     * Dark theme's floor, and why it is not [MIN_OPACITY].
     *
     * The row fill is 45% white in light and 9% white in dark. In light that fill pushes
     * the row *away* from the dark ink, so the row's background has a hard floor around
     * 182/255 whatever the wallpaper does and the text is safe at any container opacity.
     * In dark the same white fill pushes the row *towards* the light ink — the fill has
     * the wrong sign — so on a bright wallpaper the container is the only thing between
     * the ink and the wall. Measured against `design/reference-user-homescreen.jpg`
     * (mean RGB 215,210,217 — Fred's actual wallpaper), dark theme at the 0.50 floor gives
     * a 3.4:1 title and a 2.5:1 meta line; the identical sweep in light never drops below
     * 9:1. Raising the night row fill is not the fix — 35% white over a near-black
     * container is the pale slab design/BRIEF.md:81-92 explicitly rejects — so the floor
     * moves instead.
     *
     * At 0.80 the same wallpaper reads 7.1:1 title / 4.5:1 meta. The slider's whole travel
     * is mapped onto [MIN_OPACITY_DARK]..[MAX_OPACITY] in dark rather than clamped, so a
     * drag still does something at both ends of the range in both themes.
     */
    const val MIN_OPACITY_DARK = 0.80f

    /** Levels the slider quantises to. Must equal `LEVELS` in gen-glass-drawables.py. */
    const val LEVELS = 16

    private const val LIGHT_STEP = 0.03f
    private const val DARK_STEP = 0.01f

    /**
     * Base gradient stops at full alpha, ARGB, top-left → bottom-right. The canonical
     * record of the ramp; `tools/gen-glass-drawables.py` restates these as hex and is
     * what actually writes the drawables.
     *
     * Light: the mockup panel-A ramp (cool grey → soft blue → warm grey).
     * Dark: panel D's navy equivalents — near-black with a blue-tinted centre.
     */
    val LIGHT_STOPS = intArrayOf(0xFFF4F5FA.toInt(), 0xFFDFE6F9.toInt(), 0xFFF1F0F6.toInt())
    val DARK_STOPS = intArrayOf(0xFF181B27.toInt(), 0xFF222A44.toInt(), 0xFF14161F.toInt())

    /**
     * Slider/DataStore value -> a safe opacity. Null (never set), NaN, or out-of-range
     * values all land inside the contract: absent -> the default, wild -> clamped.
     */
    fun clampOpacity(raw: Float?): Float {
        if (raw == null || raw.isNaN()) return DEFAULT_OPACITY
        return raw.coerceIn(MIN_OPACITY, MAX_OPACITY)
    }

    /** The light-theme opacity a level draws at: 0.50, 0.53, … 0.95. */
    fun opacityAtLevel(level: Int): Float =
        MIN_OPACITY + LIGHT_STEP * level.coerceIn(0, LEVELS - 1)

    /** The dark-theme opacity a level draws at: 0.80, 0.81, … 0.95. See [MIN_OPACITY_DARK]. */
    fun darkOpacityAtLevel(level: Int): Float =
        MIN_OPACITY_DARK + DARK_STEP * level.coerceIn(0, LEVELS - 1)

    /**
     * The stored float -> the level whose drawable the widget draws. Rounds to the nearest
     * level, so the 0.74 default lands on level 8 and the ends of the slider land on 0 and
     * [LEVELS] - 1 exactly.
     */
    fun levelFor(raw: Float?): Int {
        val o = clampOpacity(raw)
        return Math.round((o - MIN_OPACITY) / LIGHT_STEP).coerceIn(0, LEVELS - 1)
    }

    /**
     * The gradient stops with each alpha scaled by [opacity]. Pure int math, and the
     * specification the generated drawables' alpha bytes have to match — see
     * `GlassSurfaceTest.the generated drawable alphas`.
     */
    fun stopColors(dark: Boolean, opacity: Float): IntArray {
        val base = if (dark) DARK_STOPS else LIGHT_STOPS
        val o = opacity.coerceIn(0f, 1f)
        return IntArray(base.size) { i ->
            val c = base[i]
            val a = (((c ushr 24) and 0xFF) * o + 0.5f).toInt().coerceIn(0, 255)
            (a shl 24) or (c and 0x00FFFFFF)
        }
    }
}
